import Head from "next/head";
import { useMemo } from "react";
import styles from "../styles/Home.module.css";
import useMessages from "./useMessages";

export default function Home() {
  const messages = useMessages();

  const messagesBySender = useMemo(
    () =>
      messages.reduce((r, a) => {
        r[a.from] = r[a.from] || [];
        r[a.from].push(a);
        return r;
      }, Object.create(null)),
    [messages]
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Receiving SMS on the Browser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Try sending an SMS to {process.env.NEXT_PUBLIC_PHONE_NUMBER}.
        </h1>
        <div>Refresh the page to clear the contents.</div>

        <div className={styles.grid}>
          {Object.keys(messagesBySender).map((from) => (
            <div key={from}>
              <div className={styles.sender}>{from}</div>
              <div>
                {messagesBySender[from].map((msg) => (
                  <div key={msg.id} className={styles.message}>
                    {msg.body}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
